version: 2.1

orbs:
  android: circleci/android@3.0.2

jobs:
  build:
    docker:
      - image: cimg/android:2024.11
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: gradle-v1
      - run:
          name: Chmod Gradlew
          command: chmod +x ./gradlew
      - android/resolve-dependencies
      - android/save-gradle-cache:
          cache-prefix: gradle-v1
      - android/build
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks

  ui_test:
    executor: android/default
    steps:
      - checkout
      - android/restore_gradle_cache:
          cache-prefix: gradle-v1
      - android/setup-emulator:
          api-level: 30
          target: default
          abi: x86_64
      - android/start-emulator
      - run:
          name: Run Instrumentation Tests
          command: ./gradlew connectedDebugAndroidTest
      - android/save-gradle-cache:
          cache-prefix: gradle-v1

  unit_test:
    executor: android/default
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: gradle-v1
      - run:
          name: Run Unit Tests
          command: ./gradlew clean test
      - android/save-gradle-cache:
          cache-prefix: gradle-v1

workflows:
  build_and_test:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - ui_test:
          requires:
            - build