version: '2.1'
orbs:
  android: circleci/android@3.0.0
jobs:
  build:
    docker:
      - image: cimg/android:2024.11-ndk
    steps:
      - checkout
      - android/accept-licenses
      - run:
          name: Chmod Gradlew
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks


#  test:
#    executor:
#      name: android/android_machine
#      resource_class: large
#      tag: default
#    steps:
#      - checkout
#      - run:
#          name: Chmod permissions
#          command: chmod +x ./gradlew
#      - android/create_avd:
#          avd_name: myavd
#          install: true
#          system_image: system-images;android-31;default;x86_64
#      - android/start_emulator:
#          avd_name: myavd
#          no_window: true
#          restore_gradle_cache_prefix: v1a
#      - android/run_tests
#      - android/save_gradle_cache:
#          cache_prefix: v1a
#workflows:
#  test:
#    jobs:
#      - test

workflows:
  build:
    jobs:
      - build